version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: fastreading_postgres
    restart: always
    environment:
      POSTGRES_DB: fastreading_local
      POSTGRES_USER: fastreading_user
      POSTGRES_PASSWORD: fastreading_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
